name: Android CI

on:
  push:
    branches:
      - develop
      - main

  pull_request:
    branches:
      - '**'

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BUILD_CACHE_AWS_REGION: ${{ secrets.BUILD_CACHE_AWS_REGION }}
  BUILD_CACHE_AWS_BUCKET: ${{ secrets.BUILD_CACHE_AWS_BUCKET }}
  BUILD_CACHE_AWS_ACCESS_KEY_ID: ${{ secrets.BUILD_CACHE_AWS_ACCESS_KEY_ID }}
  BUILD_CACHE_AWS_SECRET_KEY: ${{ secrets.BUILD_CACHE_AWS_SECRET_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_PR_NUM: ${{ github.event.pull_request.number }}

jobs:
  build:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: GetStream/android-ci-actions/actions/setup-java@main

      - uses: GetStream/android-ci-actions/actions/gradle-cache@main

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug --scan

  spotless:
    name: Spotless
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - uses: GetStream/android-ci-actions/actions/setup-java@main
      - name: Run Spotless
        run: ./gradlew spotlessCheck --scan
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - uses: GetStream/android-ci-actions/actions/setup-java@main
      - name: Run Lint
        run: ./gradlew lint

  unitTest:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: GetStream/android-ci-actions/actions/setup-java@main

      - uses: GetStream/android-ci-actions/actions/gradle-cache@main

      - name: Run unit tests
        run: ./gradlew :stream-feeds-android-client:koverXmlReportDebug --scan --stacktrace

      - name: Unit tests results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: unit-tests-results
          path: stream-feeds-android/build/reports/tests/testDebugUnitTest/index.html

      - uses: GetStream/android-ci-actions/actions/setup-ruby@main

      - name: Sonar
        run: ./gradlew sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
