name: PR checklist

on:
  pull_request_target:
    types: [ opened, edited, synchronize, labeled, unlabeled, reopened ]

permissions:
  contents: read
  pull-requests: write
  issues: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-checklist:
    uses: GetStream/android-ci-actions/.github/workflows/pr-quality.yml@main
    secrets: inherit
